import { MeteringPointType } from "@energinet-datahub/dh/shared/data-access-api";

export const MeteringPointTypeMap = {
    meteringPointId: ["All"],
    settlementMethod: [MeteringPointType.E17],
    physicalStatusOfMeteringPoint: ["All"],
    scheduledMeterReadingDate: [MeteringPointType.E17], // E17 yellow??
    typeOfMeteringPoint: ["All"],
    subTypeOfMeteringPoint: ["All"],
    meterReadingOccurence: ["All"],
    netSettlementGroup: [MeteringPointType.E17, MeteringPointType.E18],
    supplyStart: [MeteringPointType.E17, MeteringPointType.E18],
    ratedCurrent: ["All"],
    ratedCapacity: ["All"],
    meteringGridArea: ["All"],
    inAreaCode: [MeteringPointType.E20],
    outAreaCode: [MeteringPointType.E20],
    productionObligation: [MeteringPointType.E18],
    powerPlantGsrnNumber: [
        MeteringPointType.E17,
        MeteringPointType.E18,
        MeteringPointType.D01,
        MeteringPointType.D04,
        MeteringPointType.D05,
        MeteringPointType.D06,
        MeteringPointType.D07,
        MeteringPointType.D08,
        MeteringPointType.D09,
        MeteringPointType.D10,
        MeteringPointType.D11,
        MeteringPointType.D12,
        MeteringPointType.D17,
        MeteringPointType.D18
    ],
    locationDescription: ["All"],
    electricitySupplier: [MeteringPointType.E17, MeteringPointType.E18],
    productType: ["All"],
    unitType: ["All"],
    disconnectionType: [MeteringPointType.E17, MeteringPointType.E18],
    connectionType: [MeteringPointType.E17, MeteringPointType.E18],
    capacity: [
        MeteringPointType.E17,
        MeteringPointType.E18,
        MeteringPointType.D01,
        MeteringPointType.D04,
        MeteringPointType.D05,
        MeteringPointType.D06,
        MeteringPointType.D07,
        MeteringPointType.D08,
        MeteringPointType.D09,
        MeteringPointType.D10,
        MeteringPointType.D11,
        MeteringPointType.D12,
        MeteringPointType.D17,
        MeteringPointType.D18
    ],
    assetType: [
        MeteringPointType.E17,
        MeteringPointType.E18,
        MeteringPointType.D01,
        MeteringPointType.D04,
        MeteringPointType.D05,
        MeteringPointType.D06,
        MeteringPointType.D07,
        MeteringPointType.D08,
        MeteringPointType.D09,
        MeteringPointType.D10,
        MeteringPointType.D11,
        MeteringPointType.D12,
        MeteringPointType.D17,
        MeteringPointType.D18
    ],
    effectiveDate: ["All"],
    streetName: ["All"],
    streetCode: ["All"],
    buildingNumber: ["All"],
    floorId: ["All"],
    roomId: ["All"],
    citySubDivName: ["All"],
    postCode: ["All"],
    cityName: ["All"],
    municipalityCode: ["All"],
    countryCode: ["All"],
    mPAddressWashInstruction: [MeteringPointType.E17, MeteringPointType.E18, MeteringPointType.E20],
    darReference: ["All"],
    meterIdentification: [
        MeteringPointType.E17,
        MeteringPointType.E18,
        MeteringPointType.E20,
        MeteringPointType.D01,
        MeteringPointType.D02,
        MeteringPointType.D04,
        MeteringPointType.D05,
        MeteringPointType.D06,
        MeteringPointType.D07,
        MeteringPointType.D08,
        MeteringPointType.D09,
        MeteringPointType.D10,
        MeteringPointType.D11,
        MeteringPointType.D12,
        MeteringPointType.D17,
        MeteringPointType.D18,
        MeteringPointType.D20
    ],
    originalBusinessDocument: ["All"],
    childMeteringPoint: [MeteringPointType.E17, MeteringPointType.E18, MeteringPointType.E20],
    parentMeteringPoint: [
        MeteringPointType.D01,
        MeteringPointType.D02,
        MeteringPointType.D04,
        MeteringPointType.D05,
        MeteringPointType.D06,
        MeteringPointType.D07,
        MeteringPointType.D08,
        MeteringPointType.D09,
        MeteringPointType.D10,
        MeteringPointType.D11,
        MeteringPointType.D12,
        MeteringPointType.D14,
        MeteringPointType.D15,
        MeteringPointType.D17,
        MeteringPointType.D18,
        MeteringPointType.D20,
        MeteringPointType.D99
    ]
};