flag_management:
  default_rules: # the rules that will be followed for any flag added, generally
    carryforward: true
  individual_flags: # exceptions to the default rules above, stated flag by flag
    - name: business
      paths:
      - source/Energinet.DataHub.MarketParticipant.Application
      - source/Energinet.DataHub.MarketParticipant.Common
      - source/Energinet.DataHub.MarketParticipant.Domain
      - source/Energinet.DataHub.MarketParticipant.EntryPoint.Organization
      - source/Energinet.DataHub.MarketParticipant.EntryPoint.WebApi
      - source/Energinet.DataHub.MarketParticipant.Infrastructure
      - source/Energinet.DataHub.MarketParticipant.Utilities
    - name: clientlibraries
      paths:
      - source/Energinet.DataHub.MarketParticipant.Client
      - source/Energinet.DataHub.MarketParticipant.Integration.Model