/**
 * i18n Codegen Script
 *
 * Scans all Nx projects for `src/i18n/da.json` files and generates:
 * 1. A centralized types file with nested TypeScript interfaces per scope
 *    and a TranslationScopeMap for type-safe scope lookup
 * 2. A centralized providers file with Transloco scope providers per scope
 *
 * Usage: npx tsx tools/i18n-codegen/codegen.ts
 */

import { createProjectGraphAsync } from '@nx/devkit';
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'fs';
import { join, relative, dirname } from 'path';

const OUTPUT_DIR = 'libs/dh/shared/domain/src/generated/i18n';
const TYPES_OUTPUT = join(OUTPUT_DIR, 'types.ts');
const PROVIDERS_OUTPUT = join(OUTPUT_DIR, 'providers.ts');

// --- Type generation helpers ---

function generateInterfaceType(obj: Record<string, unknown>, indent: string): string {
  const lines: string[] = ['{'];

  for (const [key, value] of Object.entries(obj)) {
    // Keys that aren't valid identifiers need quoting
    const safeKey = /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(key) ? key : `'${key}'`;

    if (typeof value === 'object' && value !== null && !Array.isArray(value)) {
      const nested = generateInterfaceType(value as Record<string, unknown>, indent + '  ');
      lines.push(`${indent}  ${safeKey}: ${nested};`);
    } else {
      lines.push(`${indent}  ${safeKey}: string;`);
    }
  }

  lines.push(`${indent}}`);
  return lines.join('\n');
}

function toPascalCase(str: string): string {
  return str
    .split(/[-_]/)
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join('');
}

// --- Main ---

interface ScopeInfo {
  projectName: string;
  projectRoot: string;
  daJson: Record<string, unknown>;
}

async function main() {
  const graph = await createProjectGraphAsync();
  const scopes: ScopeInfo[] = [];

  // 1. Discover all projects with i18n/da.json
  for (const [projectName, node] of Object.entries(graph.nodes)) {
    const root = node.data.root;
    const daJsonPath = join(root, 'src/i18n/da.json');

    if (!existsSync(daJsonPath)) continue;

    const daJson = JSON.parse(readFileSync(daJsonPath, 'utf-8'));

    // Validate that en.json also exists
    const enJsonPath = join(root, 'src/i18n/en.json');
    if (!existsSync(enJsonPath)) {
      console.warn(`⚠️  Skipping ${projectName}: src/i18n/en.json not found`);
      continue;
    }

    scopes.push({ projectName, projectRoot: root, daJson });
  }

  if (scopes.length === 0) {
    console.log('No translation scopes found.');
    return;
  }

  // Sort for deterministic output
  scopes.sort((a, b) => a.projectName.localeCompare(b.projectName));

  // 2. Ensure output directory exists
  mkdirSync(OUTPUT_DIR, { recursive: true });

  // 3. Generate types file
  generateTypes(scopes);

  // 4. Generate providers file
  generateProviders(scopes);

  console.log(`✅ Generated ${scopes.length} translation scope(s):`);
  for (const scope of scopes) {
    console.log(`   - ${scope.projectName}`);
  }
}

function generateTypes(scopes: ScopeInfo[]) {
  let output = '// Auto-generated by tools/i18n-codegen — do not edit\n\n';

  for (const scope of scopes) {
    const typeName = toPascalCase(scope.projectName) + 'Translation';
    const interfaceBody = generateInterfaceType(scope.daJson, '');

    output += `export type ${typeName} = ${interfaceBody};\n\n`;
  }

  // Generate the scope map for type inference
  output += `export interface TranslationScopeMap {\n`;
  for (const scope of scopes) {
    const typeName = toPascalCase(scope.projectName) + 'Translation';
    output += `  '${scope.projectName}': ${typeName};\n`;
  }
  output += `}\n`;

  writeFileSync(TYPES_OUTPUT, output);
  console.log(`   types  → ${TYPES_OUTPUT}`);
}

function generateProviders(scopes: ScopeInfo[]) {
  const providersOutputDir = dirname(PROVIDERS_OUTPUT);

  let output = '// Auto-generated by tools/i18n-codegen — do not edit\n';
  output += "import { provideTranslocoScope } from '@jsverse/transloco';\n\n";

  for (const scope of scopes) {
    // Calculate relative path from output dir to the i18n folder
    const i18nDir = join(scope.projectRoot, 'src/i18n');
    let relPath = relative(providersOutputDir, i18nDir);

    // Ensure forward slashes and starts with ./
    relPath = relPath.split('\\').join('/');
    if (!relPath.startsWith('.')) {
      relPath = './' + relPath;
    }

    const loaderName =
      toPascalCase(scope.projectName).replace(/^./, (c) => c.toLowerCase()) + 'Loader';
    const exportName =
      toPascalCase(scope.projectName).replace(/^./, (c) => c.toLowerCase()) + 'TranslocoScope';

    output += `const ${loaderName} = ['da', 'en'].reduce(\n`;
    output += `  (acc, lang) => {\n`;
    output += `    acc[lang] = () => import('${relPath}/' + lang + '.json');\n`;
    output += `    return acc;\n`;
    output += `  },\n`;
    output += `  {} as Record<string, () => Promise<unknown>>\n`;
    output += `);\n\n`;

    output += `export const ${exportName} = [\n`;
    output += `  provideTranslocoScope({\n`;
    output += `    scope: '${scope.projectName}',\n`;
    output += `    loader: ${loaderName},\n`;
    output += `  }),\n`;
    output += `];\n\n`;
  }

  writeFileSync(PROVIDERS_OUTPUT, output.trimEnd() + '\n');
  console.log(`   providers → ${PROVIDERS_OUTPUT}`);
}

main().catch((err) => {
  console.error('i18n codegen failed:', err);
  process.exit(1);
});
