/**
 * @license
 * Copyright 2020 Energinet DataHub A/S
 *
 * Licensed under the Apache License, Version 2.0 (the "License2");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
export const document = `<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2021 rel. 3 (x64) (http://www.altova.com)-->
<cim:RequestAggregatedMeasureData_MarketDocument xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:cim="urn:ediel.org:measure:requestaggregatedmeasuredata:0:1" xsi:schemaLocation="urn:ediel.org:measure:requestaggregatedmeasuredata:0:1 urn-ediel-org-measure-requestaggregatedmeasuredata-0-1.xsd">
	<cim:mRID>JMz4tnHAddAsruwi2vok7AmkG2z5N5jZclJT</cim:mRID>
	<cim:type>E74</cim:type>
	<cim:process.processType>D03</cim:process.processType>
	<cim:businessSector.type>23</cim:businessSector.type>
	<cim:sender_MarketParticipant.mRID codingScheme="A10">5790000392551</cim:sender_MarketParticipant.mRID>
	<cim:sender_MarketParticipant.marketRole.type>MDR</cim:sender_MarketParticipant.marketRole.type>
	<cim:receiver_MarketParticipant.mRID codingScheme="A10">5790001330552</cim:receiver_MarketParticipant.mRID>
	<cim:receiver_MarketParticipant.marketRole.type>DGL</cim:receiver_MarketParticipant.marketRole.type>
	<cim:createdDateTime>2022-12-17T09:30:47Z</cim:createdDateTime>
	<cim:Series>
		<cim:mRID>scRh0duVS90EStqcVwM4iXwGy4OHytyAjeFd</cim:mRID>
		<!-- <cim:settlement_Series.version>D01</cim:settlement_Series.version> -->
		<cim:marketEvaluationPoint.type>E17</cim:marketEvaluationPoint.type>
		<cim:marketEvaluationPoint.settlementMethod>D01</cim:marketEvaluationPoint.settlementMethod>
		<cim:start_DateAndOrTime.dateTime>2023-01-01T23:00:00Z</cim:start_DateAndOrTime.dateTime>
		<cim:end_DateAndOrTime.dateTime>2022-01-22T23:00:00Z</cim:end_DateAndOrTime.dateTime>
		<cim:meteringGridArea_Domain.mRID codingScheme="NDK">804</cim:meteringGridArea_Domain.mRID>
		<!--<cim:energySupplier_MarketParticipant.mRID codingScheme="A10">7080000729821</cim:energySupplier_MarketParticipant.mRID>-->
		<cim:balanceResponsibleParty_MarketParticipant.mRID codingScheme="A10">5790001687137</cim:balanceResponsibleParty_MarketParticipant.mRID>
	</cim:Series>
</cim:RequestAggregatedMeasureData_MarketDocument>`;

// prettier-ignore
export const documentJson = {
  "NotifyAggregatedMeasureData_MarketDocument": {
    "mRID": "879262df-305b-47b9-9b84-ecdfb8c61246",
    "businessSector.type": {
      "value": "23"
    },
    "createdDateTime": "2024-01-31T08:44:11Z",
    "process.processType": {
      "value": "D05"
    },
    "receiver_MarketParticipant.mRID": {
      "codingScheme": "A10",
      "value": "5790000392551"
    },
    "receiver_MarketParticipant.marketRole.type": {
      "value": "MDR"
    },
    "sender_MarketParticipant.mRID": {
      "codingScheme": "A10",
      "value": "5790001330552"
    },
    "sender_MarketParticipant.marketRole.type": {
      "value": "DGL"
    },
    "type": {
      "value": "E31"
    },
    "Series": [
      {
        "mRID": "708bfd27-b6fb-4ed2-8324-6c5b4cead8a5",
        "version": "638421257595809732",
        "meteringGridArea_Domain.mRID": {
          "codingScheme": "NDK",
          "value": "804"
        },
        "marketEvaluationPoint.settlementMethod": {
          "value": "D01"
        },
        "marketEvaluationPoint.type": {
          "value": "E17"
        },
        "product": "8716867000030",
        "quantity_Measure_Unit.name": {
          "value": "KWH"
        },
        "Period": {
          "resolution": "PT15M",
          "timeInterval": {
            "start": {
              "value": "2023-01-31T23:00Z"
            },
            "end": {
              "value": "2023-02-28T23:00Z"
            }
          },
          "Point": [
            {
              "position": {
                "value": 1
              },
              "quality": {
                "value": "A05"
              },
              "quantity": 76.681
            },
            {
              "position": {
                "value": 2
              },
              "quality": {
                "value": "A05"
              },
              "quantity": 76.681
            },
            {
              "position": {
                "value": 3
              },
              "quality": {
                "value": "A05"
              },
              "quantity": 76.681
            },
            {
              "position": {
                "value": 4
              },
              "quality": {
                "value": "A05"
              },
              "quantity": 76.681
            },
            {
              "position": {
                "value": 5
              },
              "quality": {
                "value": "A05"
              },
              "quantity": 76.681
            },
            {
              "position": {
                "value": 6
              },
              "quality": {
                "value": "A05"
              },
              "quantity": 76.681
            },
            {
              "position": {
                "value": 7
              },
              "quality": {
                "value": "A05"
              },
              "quantity": 76.681
            },
            {
              "position": {
                "value": 8
              },
              "quality": {
                "value": "A05"
              },
              "quantity": 76.681
            },
            {
              "position": {
                "value": 9
              },
              "quality": {
                "value": "A05"
              },
              "quantity": 76.681
            },
            {
              "position": {
                "value": 10
              },
              "quality": {
                "value": "A05"
              },
              "quantity": 76.681
            },
            {
              "position": {
                "value": 11
              },
              "quality": {
                "value": "A05"
              },
              "quantity": 76.681
            },
            {
              "position": {
                "value": 12
              },
              "quality": {
                "value": "A05"
              },
              "quantity": 76.681
            },
            {
              "position": {
                "value": 13
              },
              "quality": {
                "value": "A05"
              },
              "quantity": 76.681
            }
          ]
        }
      }
    ]
  }
};
