#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"
. "$(dirname -- "$0")/common.sh"

if git diff-tree -r --name-only --no-commit-id HEAD@{1} HEAD | grep --quiet "bun.lockb";
then
  echo " * changes detected in bun.lockb"
  echo " * running bun install"
  bun install
  exit 0
fi
