/**
 * DataHub BFF
 * Backend-for-frontend for DataHub
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


 export interface ValidationRuleDto {
  name: string;
  description: string;
  ruleArray: Array<ValidationRuleItemDto>;
}

export interface ValidationRuleItemDto {

    rule: string;
    action: string;
    text: string;
}

export interface ValidationRuleResultDto {
  status: string;
  statusText: string;
  alertMessage: string;
  resultArray: Array<ValidationRuleResultItemDto>;
}

export interface ValidationRuleResultItemDto {
  fieldName: string;
  action: string;
    text: string;
}
