# Copyright 2020 Energinet DataHub A/S
#
# Licensed under the Apache License, Version 2.0 (the "License2");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: DH CI Frontend
on:
  workflow_call: {}
env:
  # NX_BRANCH: ${{ github.event.number }}
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
  # NX_CI_EXECUTION_ID: ${{ github.run_id }}

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          filter: tree:0
          fetch-depth: 0
      - run: bunx nx start-ci-run --distribute-on="3 linux-large" --stop-agents-after="build"

      - name: Setup toolchains with mise
        uses: jdx/mise-action@v3

      - run: bun install --frozen-lockfile
      - uses: nrwl/nx-set-shas@v4

      - run: bun nx affected --parallel -t lint test build
      # - run: bun nx affected -t e2e
      # Nx Cloud recommends fixes for failures to help you get CI green faster. Learn more: https://nx.dev/ci/features/self-healing-ci
      - run: bun nx fix-ci
        if: always()
