# Copyright 2020 Energinet DataHub A/S
#
# Licensed under the Apache License, Version 2.0 (the "License2");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: DH CI Frontend
permissions:
  contents: write

on:
  workflow_call: {}
env:
  NX_BRANCH: ${{ github.event.number }}
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
  NX_CI_EXECUTION_ID: ${{ github.run_id }}

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          filter: tree:0
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref || github.sha }}
          repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}

      - name: Setup toolchains with mise
        uses: jdx/mise-action@v3

      - run: bunx nx start-ci-run --distribute-on="3 linux-large" --stop-agents-after="build"
      - run: bun install --frozen-lockfile
      - uses: nrwl/nx-set-shas@v4
      - name: "Lint and fix affected projects"
        run: bun run affected:lint:fix
      - name: Format projects and configuration files
        run: bun run format

      - name: Commit lint and formatted files
        if: ${{ github.event.pull_request.head.ref }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A

          if git diff --cached --quiet; then
            exit 0
          fi

          git commit -m "style: format and lint"
          git push origin HEAD:${{ github.event.pull_request.head.ref }} --force-with-lease
      - run: bun nx affected --parallel -t test build
      # - run: bun nx affected -t e2e
      # Nx Cloud recommends fixes for failures to help you get CI green faster. Learn more: https://nx.dev/ci/features/self-healing-ci
      - run: bun nx fix-ci
        if: always()
