# Copyright 2020 Energinet DataHub A/S
#
# Licensed under the Apache License, Version 2.0 (the "License2");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
name: Watt CI - Package

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NX_BRANCH: ${{ github.event.number }}
  NX_CI_EXECUTION_ID: ${{ github.run_id }}

on:
  pull_request:
    branches:
      - main

jobs:
  changes:
    uses: ./.github/workflows/detect-changes.yml

  prepare:
    name: prepare
    needs: changes
    if: ${{ needs.changes.outputs.watt_frontend == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Generate Github token
        uses: Energinet-DataHub/.github/.github/actions/github-create-token@v14
        id: generate_token
        with:
          app_id: ${{ vars.dh3serviceaccount_appid }}
          private_key: ${{ secrets.dh3serviceaccount_privatekey }}

      - name: Check out source code
        uses: actions/checkout@v5
        with:
          token: ${{ steps.generate_token.outputs.token }}
          ref: ${{ github.head_ref }}

      - name: Bun setup
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: package.json

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Update peer dependencies
        run: bun nx g @energinet-datahub/tools/package:peer-dependencies --project="watt" --packageJson="libs/watt/package/package.json"

      - name: Commit peer dependencies
        run: |
          git add libs/watt/package/package.json || cd .
          git commit -m "chore(watt): update peer dependencies" || cd .

      - name: Bump version
        run: bun nx g @energinet-datahub/tools/package:version-bump --packageJson="libs/watt/package/package.json"

      - name: Commit version
        run: |
          git add libs/watt/package/package.json || cd .
          git commit -m "chore(watt): bump version" || cd .

      - name: Push changes
        run: |
          git push origin --force-with-lease || cd .
